import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import cypress from 'eslint-plugin-cypress';

const config = [
  {
    ignores: ['public/sw.js', 'public/workbox-*.js', 'jest.config.js', 'postcss.config.js', '__mocks__/**/*'],
  },
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    ignores: ['cypress/**/*.{js,ts}'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        React: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        NodeJS: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        RequestInit: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        SharedWorker: 'readonly',
        ServiceWorker: 'readonly',
        Notification: 'readonly',
        NotificationPermission: 'readonly',
        PermissionStatus: 'readonly',
        Permissions: 'readonly',
        MediaDevices: 'readonly',
        MediaStream: 'readonly',
        MediaStreamTrack: 'readonly',
        RTCPeerConnection: 'readonly',
        RTCSessionDescription: 'readonly',
        RTCIceCandidate: 'readonly',
        GeolocationPosition: 'readonly',
        GeolocationCoordinates: 'readonly',
        GeolocationPositionError: 'readonly',
        Geolocation: 'readonly',
        Storage: 'readonly',
        StorageEvent: 'readonly',
        CSSStyleDeclaration: 'readonly',
        CSSRule: 'readonly',
        CSSStyleSheet: 'readonly',
        DOMTokenList: 'readonly',
        DOMStringMap: 'readonly',
        DOMRect: 'readonly',
        DOMRectReadOnly: 'readonly',
        IntersectionObserver: 'readonly',
        IntersectionObserverEntry: 'readonly',
        MutationObserver: 'readonly',
        MutationRecord: 'readonly',
        ResizeObserver: 'readonly',
        ResizeObserverEntry: 'readonly',
        PerformanceObserver: 'readonly',
        PerformanceEntry: 'readonly',
        Performance: 'readonly',
        PerformanceTiming: 'readonly',
        PerformanceNavigation: 'readonly',
        HTMLElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLFormElement: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        EventListener: 'readonly',
        EventListenerOrEventListenerObject: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        FocusEvent: 'readonly',
        ChangeEvent: 'readonly',
        FormEvent: 'readonly',
        CloseEvent: 'readonly',
        MessageEvent: 'readonly',
        TouchEvent: 'readonly',
        InputEvent: 'readonly',
        SubmitEvent: 'readonly',
        PointerEvent: 'readonly',
        WheelEvent: 'readonly',
        DragEvent: 'readonly',
        ClipboardEvent: 'readonly',
        AnimationEvent: 'readonly',
        TransitionEvent: 'readonly',
        ProgressEvent: 'readonly',
        ErrorEvent: 'readonly',
        BeforeUnloadEvent: 'readonly',
        PopStateEvent: 'readonly',
        HashChangeEvent: 'readonly',
        PageTransitionEvent: 'readonly',
        UIEvent: 'readonly',
        CompositionEvent: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        ImageData: 'readonly',
        MediaQueryList: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        requestIdleCallback: 'readonly',
        cancelIdleCallback: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        Crypto: 'readonly',
        SubtleCrypto: 'readonly',
        performance: 'readonly',
        PerformanceMark: 'readonly',
        PerformanceMeasure: 'readonly',
        PerformanceResourceTiming: 'readonly',
        PerformancePaintTiming: 'readonly',
        PerformanceObserverEntryList: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        XPathResult: 'readonly',
        Range: 'readonly',
        Selection: 'readonly',
        TreeWalker: 'readonly',
        NodeIterator: 'readonly',
        ResizeObserverSize: 'readonly',
        NodeList: 'readonly',
        HTMLCollection: 'readonly',
        NamedNodeMap: 'readonly',
        Attr: 'readonly',
        CharacterData: 'readonly',
        Comment: 'readonly',
        DocumentFragment: 'readonly',
        DocumentType: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        Text: 'readonly',
        CDATASection: 'readonly',
        ProcessingInstruction: 'readonly',
        EntityReference: 'readonly',
        Entity: 'readonly',
        Notation: 'readonly',
        XMLDocument: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLAreaElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLBRElement: 'readonly',
        HTMLBaseElement: 'readonly',
        HTMLBodyElement: 'readonly',
        HTMLDataElement: 'readonly',
        HTMLDataListElement: 'readonly',
        HTMLDetailsElement: 'readonly',
        HTMLDialogElement: 'readonly',
        HTMLEmbedElement: 'readonly',
        HTMLFieldSetElement: 'readonly',
        HTMLHRElement: 'readonly',
        HTMLHeadElement: 'readonly',
        HTMLHtmlElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLLegendElement: 'readonly',
        HTMLLinkElement: 'readonly',
        HTMLMapElement: 'readonly',
        HTMLMetaElement: 'readonly',
        HTMLMeterElement: 'readonly',
        HTMLModElement: 'readonly',
        HTMLOListElement: 'readonly',
        HTMLObjectElement: 'readonly',
        HTMLOptGroupElement: 'readonly',
        HTMLOptionElement: 'readonly',
        HTMLOutputElement: 'readonly',
        HTMLParamElement: 'readonly',
        HTMLPictureElement: 'readonly',
        HTMLPreElement: 'readonly',
        HTMLProgressElement: 'readonly',
        HTMLQuoteElement: 'readonly',
        HTMLScriptElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLSlotElement: 'readonly',
        HTMLSourceElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLStyleElement: 'readonly',
        HTMLTableCaptionElement: 'readonly',
        HTMLTableCellElement: 'readonly',
        HTMLTableColElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLTableRowElement: 'readonly',
        HTMLTableSectionElement: 'readonly',
        HTMLTemplateElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLTimeElement: 'readonly',
        HTMLTitleElement: 'readonly',
        HTMLTrackElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLUnknownElement: 'readonly',
        HTMLVideoElement: 'readonly',
        SVGElement: 'readonly',
        SVGGraphicsElement: 'readonly',
        SVGSVGElement: 'readonly',
        CSSStyleRule: 'readonly',
        CSSImportRule: 'readonly',
        CSSMediaRule: 'readonly',
        CSSFontFaceRule: 'readonly',
        CSSPageRule: 'readonly',
        CSSNamespaceRule: 'readonly',
        CSSKeyframesRule: 'readonly',
        CSSKeyframeRule: 'readonly',
        CSSSupportsRule: 'readonly',
        CSSConditionRule: 'readonly',
        CSSGroupingRule: 'readonly',
        MediaList: 'readonly',
        StyleSheet: 'readonly',
        StyleSheetList: 'readonly',
        Navigator: 'readonly',
        ServiceWorkerRegistration: 'readonly',
        MessageChannel: 'readonly',
        IDBDatabase: 'readonly',
        IDBVersionChangeEvent: 'readonly',
        IDBOpenDBRequest: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'off',
      ...tseslint.configs.recommended.rules,
    },
  },
  {
    files: ['**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        global: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
  },
  {
    files: [
      '**/*.test.{js,ts,tsx}',
      '**/*.spec.{js,ts,tsx}',
      '__tests__/**/*.{js,ts,tsx}',
      'jest.setup.js',
    ],
    languageOptions: {
      parser: tsparser,
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        React: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        NodeJS: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        RequestInit: 'readonly',
        Headers: 'readonly',
        HTMLElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        CloseEvent: 'readonly',
        MessageEvent: 'readonly',
        Navigator: 'readonly',
        ServiceWorkerRegistration: 'readonly',
        MessageChannel: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLFormElement: 'readonly',
        IDBDatabase: 'readonly',
        IDBVersionChangeEvent: 'readonly',
        IDBOpenDBRequest: 'readonly',
        EventListenerOrEventListenerObject: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['cypress/**/*.{js,ts}', 'tests/e2e/**/*.{js,ts}'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        cy: 'readonly',
        Cypress: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        before: 'readonly',
        after: 'readonly',
        expect: 'readonly',
        assert: 'readonly',
        context: 'readonly',
        specify: 'readonly',
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        JQuery: 'readonly',
        $: 'readonly',
        Window: 'readonly',
        KeyboardEventInit: 'readonly',
        HTMLTextAreaElement: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      cypress: cypress,
    },
    rules: {
      'cypress/no-assigning-return-values': 'error',
      'cypress/no-unnecessary-waiting': 'warn',
      'cypress/assertion-before-screenshot': 'warn',
      'cypress/no-force': 'warn',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**/*',
      '.next/**/*',
      'out/**/*',
      'build/**/*',
      'dist/**/*',
      'lib/types.d.ts',
    ],
  },
];

export default config;
